# Generated by Django 3.2.9 on 2021-11-05 23:35

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=1024)),
                ('message', models.TextField(blank=True, null=True)),
                ('recipients', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None)),
                ('html_message', models.TextField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
