# Generated by Django 3.2.9 on 2021-12-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eid',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, unique=True),
        ),
    ]
