# Generated by Django 3.2.10 on 2021-12-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='csid',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='eid',
            field=models.CharField(default='this', max_length=512, unique=True),
            preserve_default=False,
        ),
    ]
