# Generated by Django 3.2.9 on 2021-12-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_regraderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraderequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Grade increased', 'Increase'), ('Grade did not change', 'No Change')], default='Pending', max_length=512),
            preserve_default=False,
        ),
    ]
