version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=store_db
      - POSTGRES_USER=store_api
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - '5431:5432'
  smtp:
    build: .
    ports:
      - '1025:1025'
      - '8025:8025'