# Generated by Django 3.2.10 on 2022-01-18 04:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(max_length=1024)),
                ('image_src', models.TextField(blank=True)),
            ],
        ),
    ]
